node_js:
  - '12'
dist: trusty
cache:
  directories:
    - $HOME/.cache/yarn
    - node_modules
    - .next/cache
script:
  - npm i next
  - npm run build
deploy:
  provider: heroku
  api_key: $APIKEYHEROKU
  app: EventosChoclo