node_js:
  - '14'
dist: trusty
cache:
  directories:
    - $HOME/.cache/yarn
    - node_modules
    - .next/cache
script:
  - npm i react react-dom jest enzyme enzyme-adapter-react-17-updated enzyme-to-json
  - npm run test
deploy:
  provider: heroku
  api_key: $APIKEYHEROKU
  app: eventoschoclo