node_js:
  - '14'
dist: trusty
cache:
  directories:
    - $HOME/.cache/yarn
    - node_modules
    - .next/cache
script:
  - npm i -g npm
  - nvm install v14.15.5
  - npm install -g jest-cli 
  - npm run test
deploy:
  provider: heroku
  api_key: $APIKEYHEROKU
  app: eventoschoclo