node_js:
  - '14'
dist: trusty
cache:
  directories:
    - $HOME/.cache/yarn
    - node_modules
    - .next/cache
script:
  - npm i -g npm
  - nvm install v14.15.5
  - npm install jest@26.6.3 enzyme enzyme-adapter-react-17-updated jsdom jsdom-global babel-jest
  - npm i -g jest-cli@26.6.3
  - npm run test
deploy:
  provider: heroku
  api_key: $APIKEYHEROKU
  app: eventoschoclo