node_js:
  - '14'
dist: trusty
cache:
  directories:
    - $HOME/.cache/yarn
    - node_modules
    - .next/cache
script:
  - npm i -g npm
  - nvm install v14.15.5
  - npm install jest enzyme enzyme-adapter-react-17-updated jsdom jsdom-global babel-jest @testing-library/dom @testing-library/jest-dom @testing-library/react @testing-library/react-hooks
  - npm i -g jest-cli
  - npm run test
deploy:
  provider: heroku
  api_key: $APIKEYHEROKU
  app: eventoschoclo